include:
  - path: docker/postgres.yml
  - path: docker/redis.yml
  - path: docker/kafka.yml

services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "8082:8082"
      - "8083:8083"
      - "${SERVER_PLAIN_GRPC_PORT:-50051}:${SERVER_PLAIN_GRPC_PORT:-50051}"
    env_file:
      - ./Server/.env
    environment:
      - DB_HOST=db
      - KAFKA_BROKERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - db
      - kafka

  app:
    build:
      context: .
      dockerfile: App/Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_SERVER=https://floowsynkapi.raenardcruz.com
    depends_on:
      - server