// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: workflow.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArrayDataType int32

const (
	ArrayDataType_STRING   ArrayDataType = 0
	ArrayDataType_INT      ArrayDataType = 1
	ArrayDataType_BOOL     ArrayDataType = 2
	ArrayDataType_KEYVALUE ArrayDataType = 3
)

// Enum value maps for ArrayDataType.
var (
	ArrayDataType_name = map[int32]string{
		0: "STRING",
		1: "INT",
		2: "BOOL",
		3: "KEYVALUE",
	}
	ArrayDataType_value = map[string]int32{
		"STRING":   0,
		"INT":      1,
		"BOOL":     2,
		"KEYVALUE": 3,
	}
)

func (x ArrayDataType) Enum() *ArrayDataType {
	p := new(ArrayDataType)
	*p = x
	return p
}

func (x ArrayDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArrayDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[0].Descriptor()
}

func (ArrayDataType) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[0]
}

func (x ArrayDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArrayDataType.Descriptor instead.
func (ArrayDataType) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	NodeStatus_RUNNING   NodeStatus = 0
	NodeStatus_COMPLETED NodeStatus = 1
	NodeStatus_FAILED    NodeStatus = 2
	NodeStatus_INFO      NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "RUNNING",
		1: "COMPLETED",
		2: "FAILED",
		3: "INFO",
	}
	NodeStatus_value = map[string]int32{
		"RUNNING":   0,
		"COMPLETED": 1,
		"FAILED":    2,
		"INFO":      3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

type RunWorkflowIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkflowIdRequest) Reset() {
	*x = RunWorkflowIdRequest{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkflowIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkflowIdRequest) ProtoMessage() {}

func (x *RunWorkflowIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkflowIdRequest.ProtoReflect.Descriptor instead.
func (*RunWorkflowIdRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *RunWorkflowIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkflowHistoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*WorkflowHistory     `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowHistoryList) Reset() {
	*x = WorkflowHistoryList{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowHistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowHistoryList) ProtoMessage() {}

func (x *WorkflowHistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowHistoryList.ProtoReflect.Descriptor instead.
func (*WorkflowHistoryList) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowHistoryList) GetHistory() []*WorkflowHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type WorkflowHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=WorkflowId,proto3" json:"WorkflowId,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,3,opt,name=WorkflowName,proto3" json:"WorkflowName,omitempty"`
	RunDate       string                 `protobuf:"bytes,4,opt,name=RunDate,proto3" json:"RunDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowHistory) Reset() {
	*x = WorkflowHistory{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowHistory) ProtoMessage() {}

func (x *WorkflowHistory) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowHistory.ProtoReflect.Descriptor instead.
func (*WorkflowHistory) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowHistory) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowHistory) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *WorkflowHistory) GetRunDate() string {
	if x != nil {
		return x.RunDate
	}
	return ""
}

type WorkflowHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowHistoryRequest) Reset() {
	*x = WorkflowHistoryRequest{}
	mi := &file_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowHistoryRequest) ProtoMessage() {}

func (x *WorkflowHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowHistoryRequest.ProtoReflect.Descriptor instead.
func (*WorkflowHistoryRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkflowHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ReplayData          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowHistoryResponse) Reset() {
	*x = WorkflowHistoryResponse{}
	mi := &file_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowHistoryResponse) ProtoMessage() {}

func (x *WorkflowHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowHistoryResponse.ProtoReflect.Descriptor instead.
func (*WorkflowHistoryResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowHistoryResponse) GetData() []*ReplayData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReplayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Data          *NodeData              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        NodeStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=proto.NodeStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayData) Reset() {
	*x = ReplayData{}
	mi := &file_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayData) ProtoMessage() {}

func (x *ReplayData) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayData.ProtoReflect.Descriptor instead.
func (*ReplayData) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ReplayData) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReplayData) GetData() *NodeData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReplayData) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ReplayData) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_RUNNING
}

func (x *ReplayData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorkflowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkflowList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Workflows     []*Workflow            `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowList) Reset() {
	*x = WorkflowList{}
	mi := &file_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowList) ProtoMessage() {}

func (x *WorkflowList) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowList.ProtoReflect.Descriptor instead.
func (*WorkflowList) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *WorkflowList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *WorkflowList) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	Tags          []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	IsNew         *bool                  `protobuf:"varint,12,opt,name=isNew,proto3,oneof" json:"isNew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Workflow) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Workflow) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Workflow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Workflow) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Workflow) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Workflow) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Workflow) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Workflow) GetIsNew() bool {
	if x != nil && x.IsNew != nil {
		return *x.IsNew
	}
	return false
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Tabid         string                 `protobuf:"bytes,4,opt,name=tabid,proto3" json:"tabid,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Sourcex       float32                `protobuf:"fixed32,7,opt,name=sourcex,proto3" json:"sourcex,omitempty"`
	Sourcey       float32                `protobuf:"fixed32,8,opt,name=sourcey,proto3" json:"sourcey,omitempty"`
	Targetx       float32                `protobuf:"fixed32,9,opt,name=targetx,proto3" json:"targetx,omitempty"`
	Targety       float32                `protobuf:"fixed32,10,opt,name=targety,proto3" json:"targety,omitempty"`
	Animated      bool                   `protobuf:"varint,11,opt,name=animated,proto3" json:"animated,omitempty"`
	Sourcenode    *Node                  `protobuf:"bytes,12,opt,name=sourcenode,proto3" json:"sourcenode,omitempty"`
	Targetnode    *Node                  `protobuf:"bytes,13,opt,name=targetnode,proto3" json:"targetnode,omitempty"`
	Sourcehandle  string                 `protobuf:"bytes,14,opt,name=sourcehandle,proto3" json:"sourcehandle,omitempty"`
	Targethandle  string                 `protobuf:"bytes,15,opt,name=targethandle,proto3" json:"targethandle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Edge) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Edge) GetTabid() string {
	if x != nil {
		return x.Tabid
	}
	return ""
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Edge) GetSourcex() float32 {
	if x != nil {
		return x.Sourcex
	}
	return 0
}

func (x *Edge) GetSourcey() float32 {
	if x != nil {
		return x.Sourcey
	}
	return 0
}

func (x *Edge) GetTargetx() float32 {
	if x != nil {
		return x.Targetx
	}
	return 0
}

func (x *Edge) GetTargety() float32 {
	if x != nil {
		return x.Targety
	}
	return 0
}

func (x *Edge) GetAnimated() bool {
	if x != nil {
		return x.Animated
	}
	return false
}

func (x *Edge) GetSourcenode() *Node {
	if x != nil {
		return x.Sourcenode
	}
	return nil
}

func (x *Edge) GetTargetnode() *Node {
	if x != nil {
		return x.Targetnode
	}
	return nil
}

func (x *Edge) GetSourcehandle() string {
	if x != nil {
		return x.Sourcehandle
	}
	return ""
}

func (x *Edge) GetTargethandle() string {
	if x != nil {
		return x.Targethandle
	}
	return ""
}

type Node struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nodetype         string                 `protobuf:"bytes,2,opt,name=nodetype,proto3" json:"nodetype,omitempty"`
	Label            string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Data             *NodeData              `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Group            []int32                `protobuf:"varint,5,rep,packed,name=group,proto3" json:"group,omitempty"`
	Nodestyle        *string                `protobuf:"bytes,6,opt,name=nodestyle,proto3,oneof" json:"nodestyle,omitempty"`
	Inputs           []string               `protobuf:"bytes,7,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs          []string               `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Draggable        *bool                  `protobuf:"varint,9,opt,name=draggable,proto3,oneof" json:"draggable,omitempty"`
	Icon             *NodeIcon              `protobuf:"bytes,10,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Position         *NodePosition          `protobuf:"bytes,11,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Nodestatus       *string                `protobuf:"bytes,12,opt,name=nodestatus,proto3,oneof" json:"nodestatus,omitempty"`
	Type             *string                `protobuf:"bytes,13,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Dimensions       *NodeDimensions        `protobuf:"bytes,14,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	HandleBounds     *NodeHandleBounds      `protobuf:"bytes,15,opt,name=handleBounds,proto3" json:"handleBounds,omitempty"`
	ComputedPosition *NodePosition          `protobuf:"bytes,16,opt,name=computedPosition,proto3" json:"computedPosition,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetNodetype() string {
	if x != nil {
		return x.Nodetype
	}
	return ""
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetData() *NodeData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Node) GetGroup() []int32 {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Node) GetNodestyle() string {
	if x != nil && x.Nodestyle != nil {
		return *x.Nodestyle
	}
	return ""
}

func (x *Node) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Node) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Node) GetDraggable() bool {
	if x != nil && x.Draggable != nil {
		return *x.Draggable
	}
	return false
}

func (x *Node) GetIcon() *NodeIcon {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *Node) GetPosition() *NodePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Node) GetNodestatus() string {
	if x != nil && x.Nodestatus != nil {
		return *x.Nodestatus
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Node) GetDimensions() *NodeDimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Node) GetHandleBounds() *NodeHandleBounds {
	if x != nil {
		return x.HandleBounds
	}
	return nil
}

func (x *Node) GetComputedPosition() *NodePosition {
	if x != nil {
		return x.ComputedPosition
	}
	return nil
}

type NodeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Expression    *string                `protobuf:"bytes,3,opt,name=expression,proto3,oneof" json:"expression,omitempty"`
	Iteration     *int32                 `protobuf:"varint,4,opt,name=iteration,proto3,oneof" json:"iteration,omitempty"`
	Listvar       *string                `protobuf:"bytes,5,opt,name=listvar,proto3,oneof" json:"listvar,omitempty"`
	Limit         *int32                 `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Url           *string                `protobuf:"bytes,7,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Method        *string                `protobuf:"bytes,8,opt,name=method,proto3,oneof" json:"method,omitempty"`
	Headers       *NodeDataArray         `protobuf:"bytes,9,opt,name=headers,proto3,oneof" json:"headers,omitempty"`
	Payload       *string                `protobuf:"bytes,10,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	Variable      *string                `protobuf:"bytes,11,opt,name=variable,proto3,oneof" json:"variable,omitempty"`
	Message       *string                `protobuf:"bytes,12,opt,name=message,proto3,oneof" json:"message,omitempty"`
	List          *NodeDataArray         `protobuf:"bytes,13,opt,name=list,proto3,oneof" json:"list,omitempty"`
	ListVariable  *string                `protobuf:"bytes,14,opt,name=listVariable,proto3,oneof" json:"listVariable,omitempty"`
	Template      *string                `protobuf:"bytes,15,opt,name=template,proto3,oneof" json:"template,omitempty"`
	Text          *string                `protobuf:"bytes,16,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Pattern       *string                `protobuf:"bytes,17,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	ReplaceText   *string                `protobuf:"bytes,18,opt,name=replaceText,proto3,oneof" json:"replaceText,omitempty"`
	SubProcessId  *string                `protobuf:"bytes,19,opt,name=subProcessId,proto3,oneof" json:"subProcessId,omitempty"`
	Type          *string                `protobuf:"bytes,20,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Interval      *int32                 `protobuf:"varint,21,opt,name=interval,proto3,oneof" json:"interval,omitempty"`
	Weeks         *NodeDataArray         `protobuf:"bytes,22,opt,name=weeks,proto3,oneof" json:"weeks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeData) Reset() {
	*x = NodeData{}
	mi := &file_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeData) ProtoMessage() {}

func (x *NodeData) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeData.ProtoReflect.Descriptor instead.
func (*NodeData) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *NodeData) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NodeData) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *NodeData) GetExpression() string {
	if x != nil && x.Expression != nil {
		return *x.Expression
	}
	return ""
}

func (x *NodeData) GetIteration() int32 {
	if x != nil && x.Iteration != nil {
		return *x.Iteration
	}
	return 0
}

func (x *NodeData) GetListvar() string {
	if x != nil && x.Listvar != nil {
		return *x.Listvar
	}
	return ""
}

func (x *NodeData) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *NodeData) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *NodeData) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *NodeData) GetHeaders() *NodeDataArray {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *NodeData) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

func (x *NodeData) GetVariable() string {
	if x != nil && x.Variable != nil {
		return *x.Variable
	}
	return ""
}

func (x *NodeData) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *NodeData) GetList() *NodeDataArray {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *NodeData) GetListVariable() string {
	if x != nil && x.ListVariable != nil {
		return *x.ListVariable
	}
	return ""
}

func (x *NodeData) GetTemplate() string {
	if x != nil && x.Template != nil {
		return *x.Template
	}
	return ""
}

func (x *NodeData) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *NodeData) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *NodeData) GetReplaceText() string {
	if x != nil && x.ReplaceText != nil {
		return *x.ReplaceText
	}
	return ""
}

func (x *NodeData) GetSubProcessId() string {
	if x != nil && x.SubProcessId != nil {
		return *x.SubProcessId
	}
	return ""
}

func (x *NodeData) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *NodeData) GetInterval() int32 {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return 0
}

func (x *NodeData) GetWeeks() *NodeDataArray {
	if x != nil {
		return x.Weeks
	}
	return nil
}

type NodeDataArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ArrayDataType          `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ArrayDataType" json:"type,omitempty"`
	KeyValueItems []*KeyValue            `protobuf:"bytes,2,rep,name=keyValueItems,proto3" json:"keyValueItems,omitempty"`
	StringItems   []string               `protobuf:"bytes,3,rep,name=stringItems,proto3" json:"stringItems,omitempty"`
	IntItems      []int32                `protobuf:"varint,4,rep,packed,name=intItems,proto3" json:"intItems,omitempty"`
	BoolItems     []bool                 `protobuf:"varint,5,rep,packed,name=boolItems,proto3" json:"boolItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDataArray) Reset() {
	*x = NodeDataArray{}
	mi := &file_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDataArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDataArray) ProtoMessage() {}

func (x *NodeDataArray) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDataArray.ProtoReflect.Descriptor instead.
func (*NodeDataArray) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *NodeDataArray) GetType() ArrayDataType {
	if x != nil {
		return x.Type
	}
	return ArrayDataType_STRING
}

func (x *NodeDataArray) GetKeyValueItems() []*KeyValue {
	if x != nil {
		return x.KeyValueItems
	}
	return nil
}

func (x *NodeDataArray) GetStringItems() []string {
	if x != nil {
		return x.StringItems
	}
	return nil
}

func (x *NodeDataArray) GetIntItems() []int32 {
	if x != nil {
		return x.IntItems
	}
	return nil
}

func (x *NodeDataArray) GetBoolItems() []bool {
	if x != nil {
		return x.BoolItems
	}
	return nil
}

type NodeIcon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIcon) Reset() {
	*x = NodeIcon{}
	mi := &file_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIcon) ProtoMessage() {}

func (x *NodeIcon) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIcon.ProtoReflect.Descriptor instead.
func (*NodeIcon) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *NodeIcon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeIcon) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type NodeDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         float32                `protobuf:"fixed32,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDimensions) Reset() {
	*x = NodeDimensions{}
	mi := &file_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDimensions) ProtoMessage() {}

func (x *NodeDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDimensions.ProtoReflect.Descriptor instead.
func (*NodeDimensions) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *NodeDimensions) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *NodeDimensions) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type NodePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             *int32                 `protobuf:"varint,3,opt,name=z,proto3,oneof" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePosition) Reset() {
	*x = NodePosition{}
	mi := &file_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePosition) ProtoMessage() {}

func (x *NodePosition) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePosition.ProtoReflect.Descriptor instead.
func (*NodePosition) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *NodePosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NodePosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NodePosition) GetZ() int32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{17}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NodeHandleBounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        []*Handle              `protobuf:"bytes,1,rep,name=source,proto3" json:"source,omitempty"`
	Target        []*Handle              `protobuf:"bytes,2,rep,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHandleBounds) Reset() {
	*x = NodeHandleBounds{}
	mi := &file_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHandleBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHandleBounds) ProtoMessage() {}

func (x *NodeHandleBounds) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHandleBounds.ProtoReflect.Descriptor instead.
func (*NodeHandleBounds) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *NodeHandleBounds) GetSource() []*Handle {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *NodeHandleBounds) GetTarget() []*Handle {
	if x != nil {
		return x.Target
	}
	return nil
}

type Handle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Width         float32                `protobuf:"fixed32,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Position      string                 `protobuf:"bytes,8,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handle) Reset() {
	*x = Handle{}
	mi := &file_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handle) ProtoMessage() {}

func (x *Handle) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handle.ProtoReflect.Descriptor instead.
func (*Handle) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{19}
}

func (x *Handle) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Handle) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Handle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Handle) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Handle) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Handle) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Handle) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Handle) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"&\n" +
	"\x14RunWorkflowIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x13WorkflowHistoryList\x120\n" +
	"\ahistory\x18\x01 \x03(\v2\x16.proto.WorkflowHistoryR\ahistory\"\x7f\n" +
	"\x0fWorkflowHistory\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x1e\n" +
	"\n" +
	"WorkflowId\x18\x02 \x01(\tR\n" +
	"WorkflowId\x12\"\n" +
	"\fWorkflowName\x18\x03 \x01(\tR\fWorkflowName\x12\x18\n" +
	"\aRunDate\x18\x04 \x01(\tR\aRunDate\"(\n" +
	"\x16WorkflowHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x17WorkflowHistoryResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.proto.ReplayDataR\x04data\"\x8c\x02\n" +
	"\n" +
	"ReplayData\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.proto.NodeDataR\x04data\x12>\n" +
	"\tvariables\x18\x03 \x03(\v2 .proto.ReplayData.VariablesEntryR\tvariables\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.proto.NodeStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\vPageRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"$\n" +
	"\x12GetWorkflowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\fWorkflowList\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12-\n" +
	"\tworkflows\x18\x02 \x03(\v2\x0f.proto.WorkflowR\tworkflows\"\xdb\x02\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\x05nodes\x18\x04 \x03(\v2\v.proto.NodeR\x05nodes\x12!\n" +
	"\x05edges\x18\x05 \x03(\v2\v.proto.EdgeR\x05edges\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\x12\x1c\n" +
	"\tcreatedBy\x18\t \x01(\tR\tcreatedBy\x12\x1c\n" +
	"\tupdatedBy\x18\n" +
	" \x01(\tR\tupdatedBy\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x19\n" +
	"\x05isNew\x18\f \x01(\bH\x00R\x05isNew\x88\x01\x01B\b\n" +
	"\x06_isNew\"\xac\x03\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x14\n" +
	"\x05tabid\x18\x04 \x01(\tR\x05tabid\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x06 \x01(\tR\x06target\x12\x18\n" +
	"\asourcex\x18\a \x01(\x02R\asourcex\x12\x18\n" +
	"\asourcey\x18\b \x01(\x02R\asourcey\x12\x18\n" +
	"\atargetx\x18\t \x01(\x02R\atargetx\x12\x18\n" +
	"\atargety\x18\n" +
	" \x01(\x02R\atargety\x12\x1a\n" +
	"\banimated\x18\v \x01(\bR\banimated\x12+\n" +
	"\n" +
	"sourcenode\x18\f \x01(\v2\v.proto.NodeR\n" +
	"sourcenode\x12+\n" +
	"\n" +
	"targetnode\x18\r \x01(\v2\v.proto.NodeR\n" +
	"targetnode\x12\"\n" +
	"\fsourcehandle\x18\x0e \x01(\tR\fsourcehandle\x12\"\n" +
	"\ftargethandle\x18\x0f \x01(\tR\ftargethandle\"\xa6\x05\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bnodetype\x18\x02 \x01(\tR\bnodetype\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12(\n" +
	"\x04data\x18\x04 \x01(\v2\x0f.proto.NodeDataH\x00R\x04data\x88\x01\x01\x12\x14\n" +
	"\x05group\x18\x05 \x03(\x05R\x05group\x12!\n" +
	"\tnodestyle\x18\x06 \x01(\tH\x01R\tnodestyle\x88\x01\x01\x12\x16\n" +
	"\x06inputs\x18\a \x03(\tR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\b \x03(\tR\aoutputs\x12!\n" +
	"\tdraggable\x18\t \x01(\bH\x02R\tdraggable\x88\x01\x01\x12(\n" +
	"\x04icon\x18\n" +
	" \x01(\v2\x0f.proto.NodeIconH\x03R\x04icon\x88\x01\x01\x124\n" +
	"\bposition\x18\v \x01(\v2\x13.proto.NodePositionH\x04R\bposition\x88\x01\x01\x12#\n" +
	"\n" +
	"nodestatus\x18\f \x01(\tH\x05R\n" +
	"nodestatus\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\r \x01(\tH\x06R\x04type\x88\x01\x01\x125\n" +
	"\n" +
	"dimensions\x18\x0e \x01(\v2\x15.proto.NodeDimensionsR\n" +
	"dimensions\x12;\n" +
	"\fhandleBounds\x18\x0f \x01(\v2\x17.proto.NodeHandleBoundsR\fhandleBounds\x12?\n" +
	"\x10computedPosition\x18\x10 \x01(\v2\x13.proto.NodePositionR\x10computedPositionB\a\n" +
	"\x05_dataB\f\n" +
	"\n" +
	"_nodestyleB\f\n" +
	"\n" +
	"_draggableB\a\n" +
	"\x05_iconB\v\n" +
	"\t_positionB\r\n" +
	"\v_nodestatusB\a\n" +
	"\x05_type\"\xfb\a\n" +
	"\bNodeData\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x01R\x05value\x88\x01\x01\x12#\n" +
	"\n" +
	"expression\x18\x03 \x01(\tH\x02R\n" +
	"expression\x88\x01\x01\x12!\n" +
	"\titeration\x18\x04 \x01(\x05H\x03R\titeration\x88\x01\x01\x12\x1d\n" +
	"\alistvar\x18\x05 \x01(\tH\x04R\alistvar\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\x05H\x05R\x05limit\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\a \x01(\tH\x06R\x03url\x88\x01\x01\x12\x1b\n" +
	"\x06method\x18\b \x01(\tH\aR\x06method\x88\x01\x01\x123\n" +
	"\aheaders\x18\t \x01(\v2\x14.proto.NodeDataArrayH\bR\aheaders\x88\x01\x01\x12\x1d\n" +
	"\apayload\x18\n" +
	" \x01(\tH\tR\apayload\x88\x01\x01\x12\x1f\n" +
	"\bvariable\x18\v \x01(\tH\n" +
	"R\bvariable\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\f \x01(\tH\vR\amessage\x88\x01\x01\x12-\n" +
	"\x04list\x18\r \x01(\v2\x14.proto.NodeDataArrayH\fR\x04list\x88\x01\x01\x12'\n" +
	"\flistVariable\x18\x0e \x01(\tH\rR\flistVariable\x88\x01\x01\x12\x1f\n" +
	"\btemplate\x18\x0f \x01(\tH\x0eR\btemplate\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x10 \x01(\tH\x0fR\x04text\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\x11 \x01(\tH\x10R\apattern\x88\x01\x01\x12%\n" +
	"\vreplaceText\x18\x12 \x01(\tH\x11R\vreplaceText\x88\x01\x01\x12'\n" +
	"\fsubProcessId\x18\x13 \x01(\tH\x12R\fsubProcessId\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x14 \x01(\tH\x13R\x04type\x88\x01\x01\x12\x1f\n" +
	"\binterval\x18\x15 \x01(\x05H\x14R\binterval\x88\x01\x01\x12/\n" +
	"\x05weeks\x18\x16 \x01(\v2\x14.proto.NodeDataArrayH\x15R\x05weeks\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_valueB\r\n" +
	"\v_expressionB\f\n" +
	"\n" +
	"_iterationB\n" +
	"\n" +
	"\b_listvarB\b\n" +
	"\x06_limitB\x06\n" +
	"\x04_urlB\t\n" +
	"\a_methodB\n" +
	"\n" +
	"\b_headersB\n" +
	"\n" +
	"\b_payloadB\v\n" +
	"\t_variableB\n" +
	"\n" +
	"\b_messageB\a\n" +
	"\x05_listB\x0f\n" +
	"\r_listVariableB\v\n" +
	"\t_templateB\a\n" +
	"\x05_textB\n" +
	"\n" +
	"\b_patternB\x0e\n" +
	"\f_replaceTextB\x0f\n" +
	"\r_subProcessIdB\a\n" +
	"\x05_typeB\v\n" +
	"\t_intervalB\b\n" +
	"\x06_weeks\"\xcc\x01\n" +
	"\rNodeDataArray\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.proto.ArrayDataTypeR\x04type\x125\n" +
	"\rkeyValueItems\x18\x02 \x03(\v2\x0f.proto.KeyValueR\rkeyValueItems\x12 \n" +
	"\vstringItems\x18\x03 \x03(\tR\vstringItems\x12\x1a\n" +
	"\bintItems\x18\x04 \x03(\x05R\bintItems\x12\x1c\n" +
	"\tboolItems\x18\x05 \x03(\bR\tboolItems\"4\n" +
	"\bNodeIcon\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\">\n" +
	"\x0eNodeDimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x02R\x06height\"C\n" +
	"\fNodePosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x11\n" +
	"\x01z\x18\x03 \x01(\x05H\x00R\x01z\x88\x01\x01B\x04\n" +
	"\x02_z\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"`\n" +
	"\x10NodeHandleBounds\x12%\n" +
	"\x06source\x18\x01 \x03(\v2\r.proto.HandleR\x06source\x12%\n" +
	"\x06target\x18\x02 \x03(\v2\r.proto.HandleR\x06target\"\xaa\x01\n" +
	"\x06Handle\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x02R\x06height\x12\x16\n" +
	"\x06nodeId\x18\a \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bposition\x18\b \x01(\tR\bposition*<\n" +
	"\rArrayDataType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\a\n" +
	"\x03INT\x10\x01\x12\b\n" +
	"\x04BOOL\x10\x02\x12\f\n" +
	"\bKEYVALUE\x10\x03*>\n" +
	"\n" +
	"NodeStatus\x12\v\n" +
	"\aRUNNING\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\b\n" +
	"\x04INFO\x10\x032\xbe\x04\n" +
	"\x0fWorkflowService\x129\n" +
	"\vGetWorkflow\x12\x19.proto.GetWorkflowRequest\x1a\x0f.proto.Workflow\x128\n" +
	"\rListWorkflows\x12\x12.proto.PageRequest\x1a\x13.proto.WorkflowList\x122\n" +
	"\x0eUpdateWorkflow\x12\x0f.proto.Workflow\x1a\x0f.proto.Workflow\x122\n" +
	"\x0eCreateWorkflow\x12\x0f.proto.Workflow\x1a\x0f.proto.Workflow\x129\n" +
	"\x0eDeleteWorkflow\x12\x0f.proto.Workflow\x1a\x16.google.protobuf.Empty\x120\n" +
	"\bQuickRun\x12\x0f.proto.Workflow\x1a\x11.proto.ReplayData0\x01\x12A\n" +
	"\rRunWorkflowId\x12\x1b.proto.RunWorkflowIdRequest\x1a\x11.proto.ReplayData0\x01\x12I\n" +
	"\x13ListWorkflowHistory\x12\x16.google.protobuf.Empty\x1a\x1a.proto.WorkflowHistoryList\x12S\n" +
	"\x12GetWorkflowHistory\x12\x1d.proto.WorkflowHistoryRequest\x1a\x1e.proto.WorkflowHistoryResponseB\tZ\a./protob\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_workflow_proto_goTypes = []any{
	(ArrayDataType)(0),              // 0: proto.ArrayDataType
	(NodeStatus)(0),                 // 1: proto.NodeStatus
	(*RunWorkflowIdRequest)(nil),    // 2: proto.RunWorkflowIdRequest
	(*WorkflowHistoryList)(nil),     // 3: proto.WorkflowHistoryList
	(*WorkflowHistory)(nil),         // 4: proto.WorkflowHistory
	(*WorkflowHistoryRequest)(nil),  // 5: proto.WorkflowHistoryRequest
	(*WorkflowHistoryResponse)(nil), // 6: proto.WorkflowHistoryResponse
	(*ReplayData)(nil),              // 7: proto.ReplayData
	(*PageRequest)(nil),             // 8: proto.PageRequest
	(*GetWorkflowRequest)(nil),      // 9: proto.GetWorkflowRequest
	(*WorkflowList)(nil),            // 10: proto.WorkflowList
	(*Workflow)(nil),                // 11: proto.Workflow
	(*Edge)(nil),                    // 12: proto.Edge
	(*Node)(nil),                    // 13: proto.Node
	(*NodeData)(nil),                // 14: proto.NodeData
	(*NodeDataArray)(nil),           // 15: proto.NodeDataArray
	(*NodeIcon)(nil),                // 16: proto.NodeIcon
	(*NodeDimensions)(nil),          // 17: proto.NodeDimensions
	(*NodePosition)(nil),            // 18: proto.NodePosition
	(*KeyValue)(nil),                // 19: proto.KeyValue
	(*NodeHandleBounds)(nil),        // 20: proto.NodeHandleBounds
	(*Handle)(nil),                  // 21: proto.Handle
	nil,                             // 22: proto.ReplayData.VariablesEntry
	(*emptypb.Empty)(nil),           // 23: google.protobuf.Empty
}
var file_workflow_proto_depIdxs = []int32{
	4,  // 0: proto.WorkflowHistoryList.history:type_name -> proto.WorkflowHistory
	7,  // 1: proto.WorkflowHistoryResponse.data:type_name -> proto.ReplayData
	14, // 2: proto.ReplayData.data:type_name -> proto.NodeData
	22, // 3: proto.ReplayData.variables:type_name -> proto.ReplayData.VariablesEntry
	1,  // 4: proto.ReplayData.status:type_name -> proto.NodeStatus
	11, // 5: proto.WorkflowList.workflows:type_name -> proto.Workflow
	13, // 6: proto.Workflow.nodes:type_name -> proto.Node
	12, // 7: proto.Workflow.edges:type_name -> proto.Edge
	13, // 8: proto.Edge.sourcenode:type_name -> proto.Node
	13, // 9: proto.Edge.targetnode:type_name -> proto.Node
	14, // 10: proto.Node.data:type_name -> proto.NodeData
	16, // 11: proto.Node.icon:type_name -> proto.NodeIcon
	18, // 12: proto.Node.position:type_name -> proto.NodePosition
	17, // 13: proto.Node.dimensions:type_name -> proto.NodeDimensions
	20, // 14: proto.Node.handleBounds:type_name -> proto.NodeHandleBounds
	18, // 15: proto.Node.computedPosition:type_name -> proto.NodePosition
	15, // 16: proto.NodeData.headers:type_name -> proto.NodeDataArray
	15, // 17: proto.NodeData.list:type_name -> proto.NodeDataArray
	15, // 18: proto.NodeData.weeks:type_name -> proto.NodeDataArray
	0,  // 19: proto.NodeDataArray.type:type_name -> proto.ArrayDataType
	19, // 20: proto.NodeDataArray.keyValueItems:type_name -> proto.KeyValue
	21, // 21: proto.NodeHandleBounds.source:type_name -> proto.Handle
	21, // 22: proto.NodeHandleBounds.target:type_name -> proto.Handle
	9,  // 23: proto.WorkflowService.GetWorkflow:input_type -> proto.GetWorkflowRequest
	8,  // 24: proto.WorkflowService.ListWorkflows:input_type -> proto.PageRequest
	11, // 25: proto.WorkflowService.UpdateWorkflow:input_type -> proto.Workflow
	11, // 26: proto.WorkflowService.CreateWorkflow:input_type -> proto.Workflow
	11, // 27: proto.WorkflowService.DeleteWorkflow:input_type -> proto.Workflow
	11, // 28: proto.WorkflowService.QuickRun:input_type -> proto.Workflow
	2,  // 29: proto.WorkflowService.RunWorkflowId:input_type -> proto.RunWorkflowIdRequest
	23, // 30: proto.WorkflowService.ListWorkflowHistory:input_type -> google.protobuf.Empty
	5,  // 31: proto.WorkflowService.GetWorkflowHistory:input_type -> proto.WorkflowHistoryRequest
	11, // 32: proto.WorkflowService.GetWorkflow:output_type -> proto.Workflow
	10, // 33: proto.WorkflowService.ListWorkflows:output_type -> proto.WorkflowList
	11, // 34: proto.WorkflowService.UpdateWorkflow:output_type -> proto.Workflow
	11, // 35: proto.WorkflowService.CreateWorkflow:output_type -> proto.Workflow
	23, // 36: proto.WorkflowService.DeleteWorkflow:output_type -> google.protobuf.Empty
	7,  // 37: proto.WorkflowService.QuickRun:output_type -> proto.ReplayData
	7,  // 38: proto.WorkflowService.RunWorkflowId:output_type -> proto.ReplayData
	3,  // 39: proto.WorkflowService.ListWorkflowHistory:output_type -> proto.WorkflowHistoryList
	6,  // 40: proto.WorkflowService.GetWorkflowHistory:output_type -> proto.WorkflowHistoryResponse
	32, // [32:41] is the sub-list for method output_type
	23, // [23:32] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	file_workflow_proto_msgTypes[9].OneofWrappers = []any{}
	file_workflow_proto_msgTypes[11].OneofWrappers = []any{}
	file_workflow_proto_msgTypes[12].OneofWrappers = []any{}
	file_workflow_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
