# Use the official PostgreSQL image
FROM postgres:17.2-alpine

# Uncomment the following lines to set the default username and password
# ENV POSTGRES_USER=
# ENV POSTGRES_PASSWORD=
ENV POSTGRES_DB=floowsynk

# Expose the PostgreSQL port
EXPOSE 5432

# Run PostgreSQL when the container starts
CMD ["postgres"]